services:
  aipan-netdisk-search:
    image: unilei/aipan-netdisk-search:latest
    container_name: aipan-netdisk-search-app
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "3001:3001"
